# Generated by Django 3.0.8 on 2020-07-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brimo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='imagefile',
            field=models.ImageField(upload_to='images', verbose_name='Bildefil'),
        ),
    ]
