# Generated by Django 3.0.8 on 2020-07-04 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brimo', '0002_auto_20200704_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Navn'),
        ),
        migrations.CreateModel(
            name='Juxtaposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Navn')),
                ('after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juxtaposition_after', to='brimo.Image')),
                ('before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juxtaposition_before', to='brimo.Image')),
            ],
        ),
    ]
