# Generated by Django 3.0.8 on 2020-07-04 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brimo', '0003_auto_20200704_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Navn')),
                ('description', models.TextField(verbose_name='Beskrivelse')),
            ],
        ),
        migrations.AlterField(
            model_name='juxtaposition',
            name='after',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juxtaposition_after', to='brimo.Image', verbose_name='Etter'),
        ),
        migrations.AlterField(
            model_name='juxtaposition',
            name='before',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juxtaposition_before', to='brimo.Image', verbose_name='Før'),
        ),
    ]
